### PR TITLE
fix(afj): connection controller after oob

### LINKED ISSUE #503: AFJ Test Agent not starting -- not creating the Indy Pool on startup
The Aries Framework JavaScript Test Agent is not starting and as a result, all of the tests in the suite are failing.  The error seems to be with creating the Indy pool for the agent.

Here is the log from a run:

```
Starting AFJ agent ...
[2K[1G[1myarn run v1.22.17[22m
[2K[1G[2m$ /src/node_modules/.bin/ts-node src/index.ts -p 9030 -i false[22m
[32m[2022-06-02T16:15:46.916] [INFO ] [TSED] - [39mCreating agent with config {
  label: 'AFJ Bob',
  walletConfig: {
    id: 'aath-javascript-1654186546913',
    key: '00000000000000000000000000000Test01'
  },
  indyLedgers: [
    {
      id: 'main-pool',
      isProduction: false,
      genesisPath: '/tmp/genesis.txn'
    }
  ],
  endpoints: [ 'http://172.17.0.1:9031' ],
  publicDidSeed: 'my_seed_000000000000000000654742',
  autoAcceptMediationRequests: true,
  useLegacyDidSovPrefix: true,
  logger: true
}
[32m[2022-06-02T16:15:46.926] [INFO ] [TSED] - [39mInitializing wallet 'aath-javascript-1654186546913' {
  id: 'aath-javascript-1654186546913',
  key: '00000000000000000000000000000Test01'
}
libindy said: [33m3[39m command_executor Worker thread started indy::commands src/commands/mod.rs [33m127[39m
[36m[2022-06-02T16:15:46.981] [DEBUG] [TSED] - [39mWallet 'aath-javascript-1654186546913' not found
[36m[2022-06-02T16:15:46.982] [DEBUG] [TSED] - [39mCreating wallet 'aath-javascript-1654186546913' using SQLite storage
[36m[2022-06-02T16:15:48.656] [DEBUG] [TSED] - [39mWallet 'aath-javascript-1654186546913' opened with handle '3'
[36m[2022-06-02T16:15:48.656] [DEBUG] [TSED] - [39mCreating master secret with id 'aath-javascript-1654186546913' in wallet with handle '3'
[36m[2022-06-02T16:15:48.670] [DEBUG] [TSED] - [39mSuccessfully created wallet 'aath-javascript-1654186546913'
[36m[2022-06-02T16:15:48.689] [DEBUG] [TSED] - [39mStarting HTTP inbound transport { port: 9031 }
[36m[2022-06-02T16:15:48.691] [DEBUG] [TSED] - [39mStarting HTTP outbound transport
[36m[2022-06-02T16:15:48.692] [DEBUG] [TSED] - [39mConnecting to ledger pool 'main-pool' { genesisPath: '/tmp/genesis.txn' }
[36m[2022-06-02T16:15:48.699] [DEBUG] [TSED] - [39mStart server...
libindy said: [33m3[39m
```

### PR DESCRIPTION
**Pull request by TimoGlastra**
this fixes creating connections in AFJ. There's some added complexity as AFJ doesn't return a connectionId anymore (only an oob id) when creating an invitation, but only when a request is received. I've fixed this for now by just returning the out of band id, and then looking for a connection based on the out of band id later on. 

This also adds an javascript-arm dockerfile that allows to run the AFJ container on m1 macs. Tried to create one for ACA-Py but didn't succeed yet.

Next up is tests for DIDExchange (which won't work with ACA-Py yet sadly) and ICv2 with indy credentials (which should work with ACA-Py!)

Fixes #503

### CODE REVIEW

**Comment by swcurran** [comment]
@TimoGlastra -- why won't DID Exchange work with ACA-Py (yet) and what needs to happen?  Is this something on the ACA-Py side that needs to change?  Thanks!

**Comment by TimoGlastra** [comment]
AFJ doesn't support connecting with public dids (it's on the roadmap) and ACA-Py doesn't support the `did:peer` spec yet. So there's no overlap in supported did methods.

AFJ doesn't support legacy peer dids for DIDExchange

**Comment by swcurran** [comment]
Thanks.  I'll talk to the team about `peer:did` support.  That's a big deal.

**Review by swcurran — APPROVED** [review]
Looks good!  Agents now run, and most of the tests.  Looks like there is an issue with the AFJ-Backchannel and mediator tests (should they be run?).  I'll create a separate issue for that.

**Pull request merged**
