### PR TITLE
Update generate-summary-results.yml

### PR DESCRIPTION
**Pull request by ryjones**
Not on PR

Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
The same PR exclusion would need to be added to the `run-send-gen-test-results-secure` steps so the reports from the PR run are not uploaded to the Alure server.

**Review by WadeBarnes — APPROVED** [review]

**Comment by WadeBarnes** [comment]
That looks like it would work.  @nodlesh, I'll leave it to you to merge if you'd like to give it a try.  The upload to Alure should be skipped when the test is triggered by a PR.

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
@ryjones, The updates have made the two test harnesses invalid, refer to the following for details:
- https://github.com/hyperledger/aries-agent-test-harness/actions/runs/2340727953
- https://github.com/hyperledger/aries-agent-test-harness/actions/runs/2340727952

**Review by nodlesh — DISMISSED** [review]
Looks good! 👍

**Comment by nodlesh** [comment]
I'll merge it if we can get the change request approved. @WadeBarnes

**Review by WadeBarnes — APPROVED** [review]

**Comment by WadeBarnes** [comment]
Approved

**Pull request merged**
