### PR TITLE
dotnet: add present proof operations

### PR DESCRIPTION
**Pull request by TimoGlastra**
The last topic!

The .NET backchannel now supports all scenarios ACA-Py supports + 1 when using the same backchannel for all operations.

Mixing between ACA-Py and .NET still has some issues. This is partly due to the issues raised with issue credential (`@id` property in credential preview).

Is it correct ACA-Py does not support the `names` property (instead of `name`) for a proof request?

@nodlesh `proof_request_health_consent.json` contained a duplicate entry `"concentration"` which I removed from the JSON. Indy was giving errors. If this was intended, please let me know.

While creating this PR @nodlesh opened #88 to replace `requested_values` with `requested_attributes`. I added the necessary changes to this PR to save an extra roundtrip. So that PR should be merged first.

FYI - .NET doesn't support the `ack` message, and also doesn't send it after verifying a presentation. I added this to the backchannel agent to make the tests pass.

See tests results below:

<details>
  <summary>ACA-Py</summary>
  
```
Failing scenarios:
  features/0036-issue-credential.feature:69  Issue a credential with negotiation beginning from a credential request
  features/0036-issue-credential.feature:84  Issue a credential with the Holder beginning with a request and is accepted
  features/0037-present-proof.feature:73  Present Proof of specific types and proof is acknowledged -- @1.1
  features/0037-present-proof.feature:90  Present Proof where the prover and verifier are connectionless, the prover does not propose a presentation of the proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:109  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.1
  features/0037-present-proof.feature:110  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.2
  features/0037-present-proof.feature:129  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:130  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.2
  features/0037-present-proof.feature:147  Present Proof where the verifier rejects the presentation of the proof -- @1.1
  features/0037-present-proof.feature:148  Present Proof where the verifier rejects the presentation of the proof -- @1.2
  features/0160-connection.feature:72  Inviter Sends invitation for one agent second agent tries after connection
  features/0160-connection.feature:89  Inviter Sends invitation for one agent second agent tries during first share phase
  features/0160-connection.feature:102  Inviter Sends invitation for multiple agents
  features/0160-connection.feature:119  Establish a connection between two agents who already have a connection initiated from invitee
  features/0160-connection.feature:145  Establish a connection between two agents but gets a request not accepted report problem message -- @1.1
  features/0160-connection.feature:146  Establish a connection between two agents but gets a request not accepted report problem message -- @1.2

0 features passed, 3 failed, 0 skipped
12 scenarios passed, 16 failed, 0 skipped
167 steps passed, 13 failed, 55 skipped, 15 undefined
Took 7m48.330s
```

</details>

<details>
  <summary>.NET</summary>
  
```
Failing scenarios:
  features/0036-issue-credential.feature:69  Issue a credential with negotiation beginning from a credential request
  features/0036-issue-credential.feature:84  Issue a credential with the Holder beginning with a request and is accepted
  features/0037-present-proof.feature:90  Present Proof where the prover and verifier are connectionless, the prover does not propose a presentation of the proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:109  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.1
  features/0037-present-proof.feature:110  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.2
  features/0037-present-proof.feature:129  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:130  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.2
  features/0037-present-proof.feature:147  Present Proof where the verifier rejects the presentation of the proof -- @1.1
  features/0037-present-proof.feature:148  Present Proof where the verifier rejects the presentation of the proof -- @1.2
  features/0160-connection.feature:72  Inviter Sends invitation for one agent second agent tries after connection
  features/0160-connection.feature:89  Inviter Sends invitation for one agent second agent tries during first share phase
  features/0160-connection.feature:102  Inviter Sends invitation for multiple agents
  features/0160-connection.feature:119  Establish a connection between two agents who already have a connection initiated from invitee
  features/0160-connection.feature:145  Establish a connection between two agents but gets a request not accepted report problem message -- @1.1
  features/0160-connection.feature:146  Establish a connection between two agents but gets a request not accepted report problem message -- @1.2

0 features passed, 3 failed, 0 skipped
13 scenarios passed, 15 failed, 0 skipped
171 steps passed, 12 failed, 52 skipped, 15 undefined
Took 5m50.255s
```

</details>

<details>
  <summary>.NET, Bob = ACA-Py</summary>

These all fail due to the `@id` property being included by .NET
  
```
Failing scenarios:
  features/0036-issue-credential.feature:11  Issue a credential with the Holder beginning with a proposal
  features/0036-issue-credential.feature:25  Issue a credential with the Holder beginning with a proposal with negotiation
  features/0036-issue-credential.feature:41  Issue a credential with the Issuer beginning with an offer
  features/0036-issue-credential.feature:54  Issue a credential with the Issuer beginning with an offer with negotiation
  features/0036-issue-credential.feature:69  Issue a credential with negotiation beginning from a credential request
  features/0036-issue-credential.feature:84  Issue a credential with the Holder beginning with a request and is accepted
  features/0037-present-proof.feature:18  Present Proof where the prover does not propose a presentation of the proof and is acknowledged -- @1.1
  features/0037-present-proof.feature:19  Present Proof where the prover does not propose a presentation of the proof and is acknowledged -- @1.2
  features/0037-present-proof.feature:37  Present Proof of specific types and proof is acknowledged -- @1.1
  features/0037-present-proof.feature:38  Present Proof of specific types and proof is acknowledged -- @1.2
  features/0037-present-proof.feature:56  Present Proof of specific types and proof is acknowledged -- @1.1
  features/0037-present-proof.feature:73  Present Proof of specific types and proof is acknowledged -- @1.1
  features/0037-present-proof.feature:90  Present Proof where the prover and verifier are connectionless, the prover does not propose a presentation of the proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:109  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.1
  features/0037-present-proof.feature:110  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.2
  features/0037-present-proof.feature:129  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:130  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.2
  features/0037-present-proof.feature:147  Present Proof where the verifier rejects the presentation of the proof -- @1.1
  features/0037-present-proof.feature:148  Present Proof where the verifier rejects the presentation of the proof -- @1.2
  features/0160-connection.feature:72  Inviter Sends invitation for one agent second agent tries after connection
  features/0160-connection.feature:89  Inviter Sends invitation for one agent second agent tries during first share phase
  features/0160-connection.feature:102  Inviter Sends invitation for multiple agents
  features/0160-connection.feature:119  Establish a connection between two agents who already have a connection initiated from invitee
  features/0160-connection.feature:145  Establish a connection between two agents but gets a request not accepted report problem message -- @1.1
  features/0160-connection.feature:146  Establish a connection between two agents but gets a request not accepted report problem message -- @1.2

0 features passed, 3 failed, 0 skipped
3 scenarios passed, 25 failed, 0 skipped
117 steps passed, 22 failed, 96 skipped, 15 undefined
Took 7m0.057s
```

</details>

<details>
  <summary>ACA-Py, Bob = .NET</summary>
  
```
Failing scenarios:
  features/0036-issue-credential.feature:69  Issue a credential with negotiation beginning from a credential request
  features/0036-issue-credential.feature:84  Issue a credential with the Holder beginning with a request and is accepted
  features/0037-present-proof.feature:73  Present Proof of specific types and proof is acknowledged -- @1.1
  features/0037-present-proof.feature:90  Present Proof where the prover and verifier are connectionless, the prover does not propose a presentation of the proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:109  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.1
  features/0037-present-proof.feature:110  Present Proof where the prover has proposed the presentation of proof and is acknowledged -- @1.2
  features/0037-present-proof.feature:129  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.1
  features/0037-present-proof.feature:130  Present Proof where the verifier and prover are connectionless, prover has proposed the presentation of proof, and is acknowledged -- @1.2
  features/0037-present-proof.feature:147  Present Proof where the verifier rejects the presentation of the proof -- @1.1
  features/0037-present-proof.feature:148  Present Proof where the verifier rejects the presentation of the proof -- @1.2
  features/0160-connection.feature:72  Inviter Sends invitation for one agent second agent tries after connection
  features/0160-connection.feature:89  Inviter Sends invitation for one agent second agent tries during first share phase
  features/0160-connection.feature:102  Inviter Sends invitation for multiple agents
  features/0160-connection.feature:119  Establish a connection between two agents who already have a connection initiated from invitee
  features/0160-connection.feature:145  Establish a connection between two agents but gets a request not accepted report problem message -- @1.1
  features/0160-connection.feature:146  Establish a connection between two agents but gets a request not accepted report problem message -- @1.2

0 features passed, 3 failed, 0 skipped
12 scenarios passed, 16 failed, 0 skipped
167 steps passed, 13 failed, 55 skipped, 15 undefined
Took 5m6.768s
```

</details>

### CODE REVIEW

**Comment by nodlesh** [comment]
Yes I believe that dup `concentration` attribute was in error. Thanks for catching that.

**Comment by swcurran** [comment]
I'm pretty sure that ACA-Py supports the "names" attribute in proof requests.  If something needs to be changed to exercise that, please go ahead on that.

**Comment by swcurran** [comment]
This is interesting -- how to deal with it:

> FYI - .NET doesn't support the ack message, and also doesn't send it after verifying a presentation. I added this to the backchannel agent to make the tests pass.

I'm not sure.  Not an issue on this, but a larger one in the community.

**Review by swcurran — APPROVED** [review]
Looks good.  Nice work!

**Comment by TimoGlastra** [comment]
> I'm pretty sure that ACA-Py supports the "names" attribute in proof requests. If something needs to be changed to exercise that, please go ahead on that.

Hmm maybe i'm not understanding correctly, but the ACA-Py backchannel throws the following error when `send-request` operation is called. It states that `name` is "Missing data for required field" and `names` is "Unknown field".

```
Matched operation: {'rfc': '0037 Present Proof', 'command': 'X', 'response': '', 'topic': 'proof', 'method': 'POST', 'operation': 'send-request', 'id': 'Y', 'data': 'Y', 'description': 'Send a proof request in reference to a proposal', 'id_details': 'pres_exchange_id', 'data_details': 'proof_request', 'result_details': 'pres_exchange_id'}
```

```json
{
    "proof_request": {
        "requested_attributes": {
            "bioindicators_attrs": {
                 "value": {
                    "name": ["Missing data for required field."], 
                    "names": ["Unknown field."]
                }
            }
        }
    }
}
```

When using only ACA-Py for all agents this same error occurs, maybe there is something wrong with the mapping from AATH -> Backchannel -> Agent. @nodlesh?

**Comment by TimoGlastra** [comment]
> This is interesting -- how to deal with it:
> 
> > FYI - .NET doesn't support the ack message, and also doesn't send it after verifying a presentation. I added this to the backchannel agent to make the tests pass.
> 
> I'm not sure. Not an issue on this, but a larger one in the community.

When I started working on this Tomislav mentioned he could implement it in the framework. Seems like a small change, so i'll open an issue in the repo.

**Pull request merged**
