### PR TITLE
Issue Credential V2 - JSON-LD credentials

### PR DESCRIPTION
**Pull request by TimoGlastra**
This contains just the test harness part of the issue credential v2 json-ld code. The ACA-Py backchannel stuff will be added in #208

### CODE REVIEW

**Comment by TimoGlastra** [comment]
@Moopli this should be enough to issue json-ld credentials using the test harness. Let me know if I broke something, was a bit hard to test without the backchannel.

**Review by swcurran — APPROVED** [review]
I can't test this without building the BBS+ Branch (which I don't know how to do yet...), so will just approve and merge this PR.

**Comment by swcurran** [comment]
Just as a matter of interest -- @TimoGlastra -- do you know why this command on this PR branch (and on master after merging):

 `./manage run -d afgo-master -t T001.1-RFC0453 -t T001.2-RFC0453` 

would result in no tests being run and skipping all of the features, scenarios and steps?

Seems weird...

**Comment by TimoGlastra** [comment]
> I can't test this without building the BBS+ Branch (which I don't know how to do yet...), so will just approve and merge this PR.

That's the nice thing of docker. Just like the rest :)

```sh
./manage build -a acapy-bbs
LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d acapy-bbs -t @CredFormat_JSON-LD
```

> would result in no tests being run and skipping all of the features, scenarios and steps?

Seems expected. AFAIK the tags are AND. So by specifying two tags from different tests no test will match. I tried on the commit before this PR and it also doesn't run any tests.

If we somehow extend the `-t` param to accept spaces (should be doable), we could write statements like:

```
-t "@T001.1-RFC0453 or @T001.2-RFC0453"
```

--- 

Just checked, this works:

```
./manage run -d afgo-master -t T001.1-RFC0453
```

**Comment by swcurran** [comment]
Thanks, Timo.

Spaces in the -t parameters is quite difficult -- it requires some fun bash handling.  Because the parameters are passed through multiple layers, it's hard to get the quoting right.  I even put a note about that in the documentation.  

Hmmm...maybe we can come up with a way to AND/OR tags and actually pass to behave just a single "-t" parameter.

We do need to add a note about the ANDing of the parameters.

**Pull request merged**
