### PR TITLE
fix: wait for uniresolver to be ready before running tests

### PR DESCRIPTION
**Pull request by Moopli**
Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

### CODE REVIEW

**Comment by nodlesh** [comment]
Locally with the uniresolver running, 
```
./manage run -d afgo-interop -b acapy-main -v 20 -t @RFC0023 -t ~@wip -t ~@T003-RFC0023 -t ~@T004-RFC0023
Agents to be used:
  Acme - afgo-interop
  Bob - acapy-main
  Faber - afgo-interop
  Mallory - afgo-interop

waiting for ledger to start
waiting for tails server to start
waiting for uniresolver to start.\e[31m
Universal Resolver failed to start within 75 seconds.
\e[0m

\e[31m
Universal Resolver is not running.
\e[0m
```

**Comment by Moopli** [comment]
Fixed, I think - since I haven't had this error, I can't validate, but it passes CI on my fork.

**Comment by nodlesh** [comment]
Still getting an error with the latest on the implicit invitation test T005-RFC0023.
```
When "Acme" sends the request to "Bob" with the public DID                                       # features/steps/0023-did-exchange.py:78 0.211s
      Assertion Failed: resp_status 500 is not 200; {"code":2002,"message":"resolve public did[did:sov:3rv7yk6M3eEkxLR6CFPDqY]: did method read failed failed: unsupported response from DID resolver [500] header [] body [Resolve problem for did:sov:3rv7yk6M3eEkxLR6CFPDqY: Driver reported for did:sov:3rv7yk6M3eEkxLR6CFPDqY: Cannot create pool config \"_\": org.hyperledger.indy.sdk.IOException: An IO error occurred.]"}
```

**Review by nodlesh — APPROVED** [review]
That implicit invite tests is still failing locally, but I'm going to merge it to see if it passes in CI.

**Comment by Moopli** [comment]
It passed on CI on my fork, so :crossed_fingers:
I'll still see if I can make a fix for linux/mac platform compatibility issues though, since those issues can be pernicious going forward..

**Comment by nodlesh** [comment]
Woohoo! It is working in CI. 

@swcurran FYI  T005-RFC0023 - the implicit invitation test between afgo and acapy is now passing in the GHA daily runs. Afgo is using the orb service in this case.

**Pull request merged**
