### PR TITLE
Initial script to check if results change day-to-day

### PR DESCRIPTION
**Pull request by ianco**
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

Script checks allure results vs previous allure results ("same as yesterday").  I added a new workflow "acapy-full" that runs the full set of integration tests and checks that the results are "same as yesterday".  I left the 3 existing workflows as is (runs the tests we expect to pass and checkes for success).

Prev results file ("The-KGR-File-<project_id>.json") not designed to be human readable, stores the result of each test from prior run.  Script creates a new file ("New-KGR-File-<project_id>.json") that can be copied over to set a new baseline.

(the "<project_id>" matches the same name as used by the allure reporting.)

### CODE REVIEW

**Comment by swcurran** [comment]
@ianco -- don't you need a KGR file per test run?  E.g. one for the acapy-acapy, one for acapy-dotnet-b, etc.?  That's what I was thinking.   Each formalized suite execution.

**Comment by ianco** [comment]
> @ianco -- don't you need a KGR file per test run? E.g. one for the acapy-acapy, one for acapy-dotnet-b, etc.? That's what I was thinking. Each formalized suite execution.

Yes that's what I was thinking - that's what I meant by "parameters and test scope that is executed" - it depends on the agents you pick plus the set of test cases you run.

**Comment by swcurran** [comment]
Got it.  There was a PR started awhile ago that allowed the agent to specify both the dockerfile to use, and the source of the agent -- e.g. for ACA-Py, the version from PyPi or the branch or tag from github.  It would be great when we have that to drive the name of the KGR file to use.  So complicated :-).  For now, something simple.

**Comment by ianco** [comment]
> @ianco -- don't you need a KGR file per test run? E.g. one for the acapy-acapy, one for acapy-dotnet-b, etc.? That's what I was thinking. Each formalized suite execution.

Uses the allure project name to identify the "test scope".

**Comment by ianco** [comment]
@nodlesh if we adopt the workflows in this PR (i.e. no changes to the existing workflows and one new "acapy-full" workflow) we will need to add the new project to the allure server to post the results.

**Comment by nodlesh** [comment]
@ianco Sure, done.

**Comment by swcurran** [comment]
Awesome stuff! 

I have a number of notes about the overall process -- some minor, others that might need some thought.  Some of these are likely in the allure changes vs. the comparison facility, but I'll include them here:

- Typo in the file -- "No **ouput** will be shown until tests are complete."
- The lack of output is painful -- my run took a LONG time.  On the other hand, process will not normally be run with allure and interactively, so it's not a bad thing.  I'm thinking that on the "no output" line, we could add a way to monitor progress.  E.g. "In another shell run `ls -al aries-test-harness/allure/allure-results/ | wc` to check that the test runs are progressing."
- The compare results output has some issues:

```
Comparing KGR results from:  ./The-KGR-file-general.json
Result differs for: features/0023-did-exchange.feature:Establish a connection with DID Exchange between two agents with an explicit invitation:Establish a connection with DID Exchange between two agents with an explicit invitation
Saving NEW KGR results to:  ./allure-results/New-KGR-File-general.json-new
Different from yesterday
\nExit with error code 1\n
```

- The folder locations are relative to the docker run vs. where manage is run. For example, the `./The-KGR-file-general.json` is actually `./aries-test-harness/allure/The-KGR-file-general.json`
- The literal `\n`s in the last echo line.
- I think there should be instructions to say how to save the new results -- e.g. what file to put into a pull-request so that the next run matches.
- I see that there is information about how the results differ, but it looks to me like there is no "general" KGR file already existing.  How did the comparison happen?

**Review by swcurran — CHANGES_REQUESTED** [review]
I think a little bit of cleanup is needed, but super close.  Nice!

**Comment by ianco** [comment]
These are related to the Allure processing.  Not sure what would be involved to get interactive output but as you mention Allure is mainly for use with the automated testing.

> * Typo in the file -- "No **ouput** will be shown until tests are complete."
> * The lack of output is painful -- my run took a LONG time.  On the other hand, process will not normally be run with allure and interactively, so it's not a bad thing.  I'm thinking that on the "no output" line, we could add a way to monitor progress.  E.g. "In another shell run `ls -al aries-test-harness/allure/allure-results/ | wc` to check that the test runs are progressing."

**Comment by ianco** [comment]
> * The compare results output has some issues:
> 
> ```
> Comparing KGR results from:  ./The-KGR-file-general.json
> Result differs for: features/0023-did-exchange.feature:Establish a connection with DID Exchange between two agents with an explicit invitation:Establish a connection with DID Exchange between two agents with an explicit invitation
> Saving NEW KGR results to:  ./allure-results/New-KGR-File-general.json-new
> Different from yesterday
> \nExit with error code 1\n
> ```
> 
> * The folder locations are relative to the docker run vs. where manage is run. For example, the `./The-KGR-file-general.json` is actually `./aries-test-harness/allure/The-KGR-file-general.json`
> * The literal `\n`s in the last echo line.
> * I think there should be instructions to say how to save the new results -- e.g. what file to put into a pull-request so that the next run matches.
> * I see that there is information about how the results differ, but it looks to me like there is no "general" KGR file already existing.  How did the comparison happen?

Folder locations are relative to where the script is run from (i.e. docker).  I suggest adding documentation describing this, in addition to documenting how to save the new results.

There should be a "general" KGR file in the repo = "aries-test-harness/allure/The-KGR-file-general.json"

**Comment by nodlesh** [comment]
> These are related to the Allure processing. Not sure what would be involved to get interactive output but as you mention Allure is mainly for use with the automated testing.
> 
> > * Typo in the file -- "No **ouput** will be shown until tests are complete."
> > * The lack of output is painful -- my run took a LONG time.  On the other hand, process will not normally be run with allure and interactively, so it's not a bad thing.  I'm thinking that on the "no output" line, we could add a way to monitor progress.  E.g. "In another shell run `ls -al aries-test-harness/allure/allure-results/ | wc` to check that the test runs are progressing."

I'll fix the output typo. I have done some research into getting default behave output displayed why Allure is processing as well. I'll do a little more digging and specifically ask some people deep in Bahave.

**Comment by ianco** [comment]
Updated to address @swcurran feedback and update KGR files to latest test results

**Review by swcurran — APPROVED** [review]
Looks great.

**Pull request merged**
