### PR TITLE
Fixed typo in command name

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]
Thanks for catching that

**Comment by swcurran** [comment]
Dang -- I thought you could approve, @TimoGlastra . You OK with being a maintainer on this repo?

@ianco -- can you please review/approve?

**Comment by TimoGlastra** [comment]
> Dang -- I thought you could approve, @TimoGlastra . You OK with being a maintainer on this repo?

Yeah sure

**Comment by TimoGlastra** [comment]
Now I can!

**Pull request merged**
