### PR TITLE
[#538] Add general request logging for agent commands

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by swcurran** [comment]
Tried this run `./manage run -d acapy-main -t T002-RFC0036` and didn't get any contents in the `request.log` file. I deleted the .logs folder before the run and confirmed that the folder and `request.log` file was created, but it was not written to during the run.  Is it just that test that I ran, or am I missing something?

Thanks!

**Comment by tdiesler** [comment]
It works for me ...
[request.log](https://github.com/hyperledger/aries-agent-test-harness/files/9281213/request.log)

The logs directory is mapped to the test harness container [like this](https://github.com/tdiesler/aries-agent-test-harness/blob/ghi538/manage#L823) ...

```
-v "$(pwd)/.logs:/aries-test-harness/logs"
```

You could exec into the running harness container and `touch` something in `/aries-test-harness/logs` that should appear in your local .logs directory. I don't think, it has to do with your local python version, because that is fixed in the harness container.

The code that appends to the request.log is [here](https://github.com/tdiesler/aries-agent-test-harness/blob/ghi538/aries-test-harness/agent_backchannel_client.py#L69). You could try ...

```
def request_log(method, agent_url, resp_status, resp_text, payload=''):
    def sorted_payload(val):
        valdict = None
        if isinstance(val, str) and len(val) > 1 and (val[0]+val[-1]) == '{}':
            valdict = dict(json.loads(val))
        elif isinstance(val, dict):
            valdict = val
        if valdict:
            valdict = dict(sorted(valdict.items()))
            val = str({k:sorted_payload(v) for (k,v) in valdict.items()})
        return val
    print(f'Req: {method} {agent_url} {sorted_payload(payload)}')
    print(f'Res: {resp_status} {sorted_payload(resp_text)}')
    print(f'-----')
    if os.path.isdir('/aries-test-harness/logs'):
    ....
```

and see if the log shows on the harness console. In that way, we would know whether the log is called at all and whether this could be a file output issue. Note, the empty request.log is already created by the `.\manage` script - hence it would be there even when `agent_backchannel_client.py` does nothing.

Thanks for looking into this - it'll be interesting to find out why the logs are not showing for you.

**Comment by tdiesler** [comment]
Have you re-built the test harness image?

**Comment by swcurran** [comment]
😊 / facepalm.  Doh...

Looks great.

**Review by swcurran — APPROVED** [review]

**Pull request merged**
