### PR TITLE
aries-vcx: Non-mediated connection handler (remove cloud agency)

### PR DESCRIPTION
**Pull request by mirgee**
These changes replace mediated connection handler in aries-vcx with non-mediated connection handler and expose an endpoint for receiving messages on the agent itself, thus removing dependency of aries-vcx agents on cloud agency (vcxagencynode).

Signed-off-by: Miroslav Kovar <miroslav.kovar@absa.africa>

### CODE REVIEW

**Comment by swcurran** [comment]
I tried to run this and got errors.  What I did:

- Started all the AATH services
- Checked out the PR (`gh pr checkout 599`)
- Ran the runset with a no-cache build (`./manage runset ariesvcx-ariesvcx -r`)

Result was the agents failed starting up.  From the logs for Acme:

```
[0m[38;5;8m[[0m2022-11-18T23:51:14Z [0m[32mINFO [0m aries_vcx_backchannel::setup[0m[38;5;8m][0m Downloading genesis file from http://172.17.0.1:9000
[0m[38;5;8m[[0m2022-11-18T23:51:14Z [0m[32mINFO [0m aries_vcx_backchannel::setup[0m[38;5;8m][0m Storing genesis file to "/resource/genesis_file.txn"
[0m[38;5;8m[[0m2022-11-18T23:51:14Z [0m[32mINFO [0m vdrtools[0m[38;5;8m][0m new >
[0m[38;5;8m[[0m2022-11-18T23:51:14Z [0m[32mINFO [0m vdrtools[0m[38;5;8m][0m new <
[0m[38;5;8m[[0m2022-11-18T23:51:14Z [0m[32mINFO [0m aries_vcx::global::settings[0m[38;5;8m][0m Can't fetch protocol version from config (Error: Invalid Configuration
      Caused by: Cannot read "protocol_version" from settings
    ), use default one (2)
[0m[38;5;8m[[0m2022-11-18T23:51:14Z [0m[32mINFO [0m actix_server::builder[0m[38;5;8m][0m Starting 2 workers
[0m[38;5;8m[[0m2022-11-18T23:51:14Z [0m[32mINFO [0m actix_server::server[0m[38;5;8m][0m Actix runtime found; starting in Actix runtime
[0m[38;5;8m[[0m2022-11-18T23:51:20Z [0m[32mINFO [0m actix_web::middleware::logger[0m[38;5;8m][0m 172.17.0.1 "GET /agent/command/status HTTP/1.1" 200 19 "-" "curl/7.58.0" 0.000066
[0m[38;5;8m[[0m2022-11-18T23:51:22Z [0m[32mINFO [0m actix_web::middleware::logger[0m[38;5;8m][0m 172.17.0.1 "GET /agent/command/did HTTP/1.1" 200 32 "-" "Python/3.7 aiohttp/3.8.3" 0.000059
[0m[38;5;8m[[0m2022-11-18T23:51:22Z [0m[32mINFO [0m vdrtools::services::ledger[0m[38;5;8m][0m build_get_schema_request() => Ok("{\"reqId\":1668815482326438488,\"identifier\":\"2hoqvcwupRTUNkXn6ArYzs\",\"operation\":{\"type\":\"107\",\"dest\":\"MjWKaGg1CdxbVqG2cQfwgK\",\"data\":{\"name\":\"test_schema.Acme\",\"version\":\"1.0.0\"}},\"protocolVersion\":2}")
[0m[38;5;8m[[0m2022-11-18T23:51:22Z [0m[32mINFO [0m vdrtools::services::ledger[0m[38;5;8m][0m parse_response() => Err(IndyError { inner: Error("data did not match any variant of untagged enum Reply", line: 0, column: 0)
    
    Structure doesn't correspond to type. Most probably not found
    
    Item not found on ledger })
[0m[38;5;8m[[0m2022-11-18T23:51:22Z [0m[32mINFO [0m vdrtools::services::ledger[0m[38;5;8m][0m parse_get_schema_response() => Err(IndyError { inner: Error("data did not match any variant of untagged enum Reply", line: 0, column: 0)
    
    Structure doesn't correspond to type. Most probably not found
    
    Item not found on ledger })
```

Any ideas?

**Comment by mirgee** [comment]
Thank you for trying to test the changes, @swcurran ! From the logs, it seems that the agent started and, although it admittedly looks like it, this output is not indicative of an error - before creating a schema, the agent checks whether the schema is already present on the ledger, which produces this output.

I have tried running the same commands as you did on a Linux machine and had no issues running the tests, so I have little clues as to what the issue might be. Were there perhaps some more logs after those you posted? If not, can you please try again and make sure you have the latest revision checked out, your docker has sufficient resources allocated to it and no containers are running before executing the tests?

**Comment by swcurran** [comment]
Weird. Might have been some docker cleanup needed -- I did a `docker system prune` and was then able to rerun the commands and they worked.  Odd behaviour if that was the issue.

Thanks!

**Review by swcurran — APPROVED** [review]
Tested and working.

**Pull request merged**
