### PR TITLE
Did exchange test dev afgo

### PR DESCRIPTION
**Pull request by murpheux**
Afgo backchannels PR with @T001-RFC0023 and @T002-RFC0023 working 

./manage build -a afgo-master && ./manage run -d afgo-master -t @T001-RFC0023

### CODE REVIEW

**Comment by nodlesh** [comment]
I've checked out your branch and the first test fails. 
```
  Scenario: Establish a connection with DID Exchange between two agents with an explicit invitation  # features/0023-did-exchange.feature:4
    Given we have "2" agents                                                                         # features/steps/0160-connection.py:15 0.001s
      | name | role      |
      | Acme | requester |
      | Bob  | responder |
    When "Bob" sends an explicit invitation                                                          # features/steps/0023-did-exchange.py:17 5.028s
    And "Acme" receives the invitation                                                               # features/steps/0023-did-exchange.py:124 0.014s
    And "Acme" sends the request to "Bob"                                                            # features/steps/0023-did-exchange.py:153 0.008s
    And "Bob" receives the request                                                                   # features/steps/0023-did-exchange.py:172 0.002s
      Traceback (most recent call last):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0023-did-exchange.py", line 174, in step_impl
          responder_connection_id = context.connection_id_dict[responder][context.requester_name]
      KeyError: 'Acme'
```

Also, you are using storage.py, agent_backchannel.py, utils.py, from within your own afgo folder. I believe there are no differences in these files than the ones in aries-backchannels/python/. Can you use these instead of your own? 

No need to submit a new environment.properties file. This file is updated every run anyway. 

I think you left a debug statement `print(resp_json)` in the 0023-did-exchange.py file.

**Review by nodlesh — CHANGES_REQUESTED** [review]
I've checked out your branch and the first test fails.
```
  Scenario: Establish a connection with DID Exchange between two agents with an explicit invitation  # features/0023-did-exchange.feature:4
    Given we have "2" agents                                                                         # features/steps/0160-connection.py:15 0.001s
      | name | role      |
      | Acme | requester |
      | Bob  | responder |
    When "Bob" sends an explicit invitation                                                          # features/steps/0023-did-exchange.py:17 5.028s
    And "Acme" receives the invitation                                                               # features/steps/0023-did-exchange.py:124 0.014s
    And "Acme" sends the request to "Bob"                                                            # features/steps/0023-did-exchange.py:153 0.008s
    And "Bob" receives the request                                                                   # features/steps/0023-did-exchange.py:172 0.002s
      Traceback (most recent call last):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0023-did-exchange.py", line 174, in step_impl
          responder_connection_id = context.connection_id_dict[responder][context.requester_name]
      KeyError: 'Acme'
```
Also, you are using storage.py, agent_backchannel.py, utils.py, from within your own afgo folder. I believe there are no differences in these files than the ones in aries-backchannels/python/. Can you use these instead of your own?

No need to submit a new environment.properties file. This file is updated every run anyway.

I think you left a debug statement `print(resp_json)` in the 0023-did-exchange.py file.

**Comment by nodlesh** [comment]
Looking good. I haven't executed it yet, but will do that soon. After a quick look, a few things still remain that should be addressed. 

You are still using storage.py, agent_backchannel.py, utils.py, from within your own afgo folder. Can you use the ones in aries-backchannels/python/? Then remove those files from this PR?
It seems you have two sets of these files in this PR. It seems you have two sets of these files, one in aries-backchannels/afgo/python/, and the other in aries-agent-test-harness/afgo/. Please remove both sets.

No need to submit a new environment.properties file. You should remove this from this PR. 

If you can, in the 0023-did-exchange.py file, move the sleep into the afgo backchannel, by increasing the MAX_TIMEOUT? With that removed would there be any reason to submit the 0023-did-exchange.py in this PR?

In aries-backchannels/python/utils.py you have `gimport` instead of `import`. Not sure why lgtm didn't catch that.

**Comment by nodlesh** [comment]
Did a test run. 4 tests pass. I think the implicit invitation is just using an explicit invitation so we will have to get that to work in the afgo backchannel in the future. 
The way you are getting the topic for the webhook isn't ideal. There may be times when the current topic may not be the one you are expecting. It would be best to pull the topic from the webhook payload. I think I seen a topic in there. Something to consider in the future. 

The handle_out_of_band method could use a little cleanup in the future. variable connectionid should be invitationid and the message references connection instead of out_of_band. 

Otherwise looks good.

**Comment by murpheux** [comment]
> Did a test run. 4 tests pass. I think the implicit invitation is just using an explicit invitation so we will have to get that to work in the afgo backchannel in the future.
> The way you are getting the topic for the webhook isn't ideal. There may be times when the current topic may not be the one you are expecting. It would be best to pull the topic from the webhook payload. I think I seen a topic in there. Something to consider in the future.
> 
> The handle_out_of_band method could use a little cleanup in the future. variable connectionid should be invitationid and the message references connection instead of out_of_band.
> 
> Otherwise looks good.

I have the following responses, (find reply below)

    The way you are getting the topic for the webhook isn't ideal. There may be times when the current topic may not be the one you are expecting. It would be best to pull the topic from the webhook payload. I think I seen a topic in there. Something to consider in the future.

For the comment above, it was easy to get the topic from the request as the webhook being invoked with "/webhooks/topic/{topic}/" instead in afgo we are using "/webhooks", we may need to change the webhook route to carry this.

    The handle_out_of_band method could use a little cleanup in the future. variable connectionid should be invitationid and the message references connection instead of out_of_band.

For the comment above, the changes has been made. Thanks. Also I am working on T007-RFCnnnn at the moment

**Review by ianco — APPROVED** [review]
Looks good to me (pending updates requested by Sheldon of course).

**Review by nodlesh — APPROVED** [review]

**Pull request merged**
