### PR TITLE
aries-vcx: Fix revocations against acapy

### PR DESCRIPTION
**Pull request by mirgee**
Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>

### CODE REVIEW

**Review by ianco — APPROVED** [review]

**Comment by ianco** [comment]
Looks good all tests pass:

`./manage run -d acapy-main -b aries-vcx -t @RFC0036,@RFC0037,@RFC0160,@revocation -t ~@wip -t ~@DIDExchangeConnection -t ~@T002-HIPE0011 -t ~@T003-RFC0160 -t ~@T004-RFC0160 -t ~@T014-HIPE0011`

**Comment by swcurran** [comment]
While you are in there...could you please do a quick PR to update the GHA runs with ACA-Py and Aries VCX?  We should also look at the other libraries that support revocation -- I think .NET.  I don't think AFJ has that support yet.

**Comment by ianco** [comment]
> While you are in there...could you please do a quick PR to update the GHA runs with ACA-Py and Aries VCX? We should also look at the other libraries that support revocation -- I think .NET. I don't think AFJ has that support yet.

This PR includes updates for the aries-vcx/acapy and acapy/aries-vcx workflows, which other ones do we need to update?
  (We may want to create workflows for acapy-main/aries-vcx ...)

**Comment by swcurran** [comment]
Ah..sorry. I didn't look #fail .  Nevermind...

Interesting about the acapy vs. acapy-main issue.  I thought we were using ACA-Py main for all of the tests.

@nodlesh -- do we have a policy on that?  :-).   What would you recommend?

**Comment by nodlesh** [comment]
All workflows are using acapy-main.

**Comment by swcurran** [comment]
Good stuff -- that's what I thought.

**Pull request merged**
