### PR TITLE
Proposal request adjustments

### LINKED ISSUE #259: Simplify/Change Proof v1 test data to just the proposal and request
The existing data passed is
```
 "presentation_proposal": {
                "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/request-presentation",
                "comment": "This is a comment for the request for presentation.",
                "request_presentations~attach": {
                    "@id": "libindy-request-presentation-0",
                    "mime-type": "application/json",
                    "data":  data
                }
            }
```
and data is
```
data = {
                    "requested_attributes": {
                        "attr_1": {
                            "name": "attr_1",
                            "restrictions": [
                                {
                                    "schema_name": "test_schema." + context.issuer_name,
                                    "schema_version": "1.0.0"
                                }
                            ]
                        }
                    }
                }
```

we really just need the 
```
"proof_request": {
...
}
```
or 
```
"presentation_proposal": {
...
}
```

### PR DESCRIPTION
**Pull request by nodlesh**
This PR resolves the issues documented in #259 

Note the openapi spec has not been updated yet. 
 
closes #259

### CODE REVIEW

**Comment by swcurran** [comment]
Tested this and it didn't go well, I don't think.  Ran the test -- `run -d acapy-main -t ~@wip` and got these new failures vs. current main branch of AATH:

``` bash
Failing scenarios:
  features/0037-present-proof.feature:149  Present Proof where the prover has proposed the presentation of proof in response to a presentation request and is acknowledged -- @1.1 
  features/0037-present-proof.feature:150  Present Proof where the prover has proposed the presentation of proof in response to a presentation request and is acknowledged -- @1.2 
  features/0037-present-proof.feature:170  Present Proof where the prover has proposed the presentation of proof from a different credential in response to a presentation request and is acknowledged -- @1.1 
  features/0037-present-proof.feature:171  Present Proof where the prover has proposed the presentation of proof from a different credential in response to a presentation request and is acknowledged -- @1.2 
  features/0037-present-proof.feature:227  Present Proof where the prover starts with a proposal the presentation of proof and is acknowledged -- @1.1 
```

Is that expected?

**Review by TimoGlastra — DISMISSED** [review]
Haven't run, but looks good

**Comment by nodlesh** [comment]
Investigating those new failed tests. However, running with the runset tags for acapy has no failures. Like `-t @AcceptanceTest -t @AIP20 -t ~@wip`

**Comment by nodlesh** [comment]
Last commit should fix the unexpected errors in acapy reported by @swcurran above. OpenAPI Spec has been updated with the changes as well. 

This PR impacts all backchannels and all the runset configurations can be executed to verify this PR. Results should be identical to what is in main at this time.

**Review by swcurran — APPROVED** [review]
LGTM -- ran through a full ACA-Py - JavaScript test results are the same as on main.

The CI tests are failing, but that is because of a configuration issue.

**Comment by swcurran** [comment]
@nodlesh -- note that the CI tests on the PR failed because of a configuration issue.  Can you please look at those?

**Comment by nodlesh** [comment]
@swcurran Those CI test runs on this PR failed because I don't have the secrets setup in my fork. To be honest I have no idea why those 2 runsets ran as verification for this PR.

**Comment by TimoGlastra** [comment]
@nodlesh those suites now run on each PR to make it easier to check nothing has broken because of a PR

**Pull request merged**
