### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by TimoGlastra**
- Add `dotnet-master` to run backchannel with master branch of framework .NET
- Update the framework to the latest release for the normal `dotnet` backchannel
- Update documentation a bit to mention OpenAPI and .NET backchannel
- Some general cleanup and improvements.

Test scores are the same

### CODE REVIEW

**Review by swcurran — APPROVED** [review]
LGTM - testing run went well.

**Comment by swcurran** [comment]
This PR completes the work undertaken by Animo Solutions as part of the this [Code With Us opportunity](https://digital.gov.bc.ca/marketplace/opportunities/code-with-us/d359da07-d8e2-48eb-89bc-35f9f04aa09c) created by the Government of British Columbia.

Our thanks to the team from Animo -- they have done a terrific job on the project and we are very pleased with the result. We hope they will continue to contribute to Hyperledger, this repo and the Trust over IP (ToIP) work being done in the open in British Columbia.

- @jljordan42
- @swcurran 

cc @mark-a-wilson

**Comment by mark-a-wilson** [comment]
@TimoGlastra - I'm attempting to get the info you need for your invoice and assist with getting you paid. Thank you for your patience and sorry for the delay.

**Comment by TimoGlastra** [comment]
> @TimoGlastra - I'm attempting to get the info you need for your invoice and assist with getting you paid. Thank you for your patience and sorry for the delay.

Thanks for your effort @mark-a-wilson!

**Pull request merged**
