### PR TITLE
KGR fixes for the new json-ld tests

### PR DESCRIPTION
**Pull request by ianco**
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

### CODE REVIEW

**Review by nodlesh — APPROVED** [review]
👍

**Comment by TimoGlastra** [comment]
What are these KGR files? I'm still not sure what it does :-)

**Comment by swcurran** [comment]
"Known Good Results".  The idea is that on the daily runs, we include tests we know will fail (since we do that) and we raise a GHA exception (triggering an email) whenever the run produces different results than in the KGR files.  That way, we are not notified when any given test fails -- only when the results change. 

Right now, we aren't sending any GHA messages after test runs, regardless of what happens in the test runs.

**Comment by TimoGlastra** [comment]
Ah that's smart. I like it

**Pull request merged**
