### PR TITLE
Added Verity Backchannel, only connection protocol for now

### PR DESCRIPTION
**Pull request by Matt-Spence**
This is the initial work for a backchannel for the Verity Agent Service. The purpose of this is just to get the plumbing in place, more protocols will be added over time

### CODE REVIEW

**Comment by swcurran** [comment]
Testing this.  However, the DCO check was not met.  Please update the PR per the details link in the DCO. 

DCO - Developer Certificate of Origin - https://github.com/apps/dco.

**Comment by swcurran** [comment]
I ran PR, but the Verity ACME agent didn't start with this in the logs:

```bash
module.js:549
    throw err;
    ^

Error: Cannot find module '@evernym/verity-sdk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/verity_backchannel.js:6:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Commands run: 

```
./manage rebuild -a acapy-main -a verity
./manage run -d acapy-main -a verity -t @RFC0160 -t ~@wip

```

**Comment by nodlesh** [comment]
I also ran this with verity only. 
```
./manage rebuild -a verity 
./manage run -d verity -t @RFC0160 -t ~@wip
```
Failed to start the agents. Ran the backchannel outside of the manage script with a command like this, 
```
docker run -it --rm --name bob_agent --expose 8030-8033 --expose 5678 -p 8030-8033:8030-8033 -p 5678:5678 -v "$(pwd)/aries-backchannels/acapy/.build/acapy-main.data:/data-mount" -e "NGROK_NAME=" -e "DOCKERHOST=192.168.65.3" -e "AGENT_NAME=Bob" -e "LEDGER_URL=http://192.168.65.3:9000" -e "TAILS_SERVER_URL=http://192.168.65.3:6543" -e "AIP_CONFIG=20" verity-agent-backchannel -p 8030 -i false
```
The error was the same as Stephen reported above. 
```
module.js:549
    throw err;
    ^

Error: Cannot find module '@evernym/verity-sdk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/verity_backchannel.js:6:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by Matt-Spence** [comment]
It looks like these are changes that I made for debugging purposes which I forgot to revert before committing. I thought I caught all of them but it looks like I missed a few. I'll get this cleaned up

**Comment by Matt-Spence** [comment]
@swcurran @nodlesh I believe I have fixed the issue. Apologies for the long delay, I had to wait for a new release of the Verity-Sdk due to some issues with the base image I used in the Verity Dockerfile.

**Comment by nodlesh** [comment]
Looks like we are getting closer. The agents will start successfully. 
Once again I am running these commands. 
```
./manage rebuild -a verity 
./manage run -d verity -t @RFC0160 -t ~@wip
```
However, all tests fail when creating an invitation. This is the error.
```
    When "Acme" generates a connection invitation                       # features/steps/0160-connection.py:79 9.672s
      Assertion Failed: resp_status 500 is not 200; {"connection_id": "null", "state": "error, unable to create invitation", "invitation": null}
```
Any ideas?

**Comment by Matt-Spence** [comment]
@nodlesh I assume you're running a local ledger? I was unable to get a ledger to run on my local machine so I used the LEDGER_URL_CONFIG env var for testing. I did most of my testing running commands like `LEDGER_URL_CONFIG=http://dev.bcovrin.vonx.io ./manage run -d acapy-main -a verity -t @RFC0160 -t ~@wip`. Also, Verity doesn't support the invitee role so it will fail tests where it is on both sides of the interaction. Apologies, I should have noted these things earlier.

**Comment by nodlesh** [comment]
Is this the result you get when you run with that run command? 
```
0 features passed, 1 failed, 6 skipped
2 scenarios passed, 3 failed, 92 skipped
33 steps passed, 3 failed, 841 skipped, 0 undefined
Took 0m41.921s
```
If so, we may want to limit the tests executed with the run command like this. 
`LEDGER_URL_CONFIG=http://dev.bcovrin.vonx.io ./manage run -d acapy-main -a verity -t @RFC0160 -t @AcceptanceTest -t ~@wip`

**Review by nodlesh — APPROVED** [review]
👍👍

**Pull request merged**
