### PR TITLE
Refactor test harness flow control

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Switch to a main test workflow to control the flow and execution of the test harnesses.
- Uses a throttled matrix strategy to control the number of concurrent test harness workflows running at one time.
- Supports:
  - dynamic discovery of test harness workflows.
  - exclusion of specific test harness workflows.

Signed-off-by: Wade Barnes <wade@neoterictech.ca>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
This PR is based on the investigation and testing preformed for this issue; https://github.com/hyperledger/aries-agent-test-harness/issues/457

Please review and provide feed back.

Items to note:
- ~max-parallel: 7~
  - ~I have it running 7 test harnesses concurrently ATM for testing only.  We may want to bring that down to 5 and see how things go from there.  I had it set to 5 on previous runs and it took a few hours to run through all the test harnesses.~
- ~I need to remove the `push` event from the `test-harness-runner` workflow (test-runner.yml) before merging.~
- ~If we proceed with this approach (which I think is at least better than the existing approach) we'll need Ry to provision a public repo scoped PAT (named REPO_ACCESS_TOKEN) for use with the new workflow before merging.~
- All the above has been updated.

**Comment by WadeBarnes** [comment]
Latest test run can be found here; https://github.com/WadeBarnes/aries-agent-test-harness/actions/runs/2065794795
- Note: - All of the tests fail on the report upload step because I don't have Allure credentials setup so I don't pollute the reports.

**Comment by swcurran** [comment]
Way cool! I think that is excellent.

Only changes I would suggest is removing some of the comments in the script itself, and perhaps adding a section to the README (or reference to another document) about adding new runsets -- GHAs that run tests.

Love to be able to run it tonight.

**Comment by WadeBarnes** [comment]
> Only changes I would suggest is removing some of the comments in the script itself, and perhaps adding a section to the README (or reference to another document) about adding new runsets -- GHAs that run tests.

@swcurran, I've updated the workflow and added some documentation.

- max-parallel has also been set to 5 and the `push` event has been removed.

**Comment by WadeBarnes** [comment]
@ryjones, would you be able to add a public repo scoped PAT named **REPO_ACCESS_TOKEN** to this repository for use with this new test harness workflow?  The PAT only needs the `public_repo` permission, provided the account it's from already has access to the repo.

**Comment by ryjones** [comment]
@WadeBarnes done

**Comment by WadeBarnes** [comment]
> @WadeBarnes done

Thanks @ryjones

**Comment by WadeBarnes** [comment]
@swcurran, @nodlesh, @ianco, This one is ready to go if you're happy with it.  The updates and the necessary secret are all in place.

**Review by swcurran — APPROVED** [review]
Brilliant!!  Great work!

**Comment by swcurran** [comment]
Made it in time for today's run, I think :-).  Let's see how it goes.

**Pull request merged**
