### PR TITLE
javascript: add issue credential, present proof

### PR DESCRIPTION
**Pull request by TimoGlastra**
- Update Aries Framework JavaScript (will add javascript-master dockerfile soon)
- Add Issue Credential, Present Proof
- Add github actions runners for javascript-javascript acapy-javascript javascript-dotnet
    - I'm not sure if the allure project will automatically be created @nodlesh

### CODE REVIEW

**Comment by swcurran** [comment]
@TimoGlastra -- looks good. It would be good to include a line about what tests that you expect to run with this, but I ran them all and same the ones working.

@nodlesh -- we have to look at the tags, I think.  It would certainly be good to have "revocation" as a tag, so we can say '-t ~@revocation` and not run any of those.

**Review by swcurran — APPROVED** [review]
Looks good ran through all the tests.

**Comment by nodlesh** [comment]
> @nodlesh -- we have to look at the tags, I think. It would certainly be good to have "revocation" as a tag, so we can say '-t ~@revocation` and not run any of those.

We do have a @RFC0011 and a @RFC0183 tag. Those will remove the execution of revocation tests.

**Comment by nodlesh** [comment]
Allure projects `javascript`, `acapy-b-javascript`, & `javascript-b-dotnet` created.

**Pull request merged**
