### PR TITLE
chore: cleanup afgo doc

### PR DESCRIPTION
**Pull request by Moopli**
Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

### CODE REVIEW

**Comment by nodlesh** [comment]
The .md files in the docs folder are generated by the gen-interop.sh script. This script runs in a GHA to create new docs if things change. To update the contents of these docs, the header information in the test runsets yml file in the .github/workflow folder needs to be updated.

**Comment by Moopli** [comment]
@nodlesh updated

**Comment by nodlesh** [comment]
Can we remove the commits for afgo.md? Thanks.

**Comment by Moopli** [comment]
@nodlesh done

**Review by swcurran — APPROVED** [review]

**Pull request merged**
