### PR TITLE
Updated Revocation Test Scenarios

### PR DESCRIPTION
**Pull request by nodlesh**
5 New Revocation Test Scenarios completed.

### CODE REVIEW

**Review by ianco — DISMISSED** [review]

**Comment by swcurran** [comment]
When I just run this in a basic way, I get errors on all the revocation tests.  I assume that is an ordering issue?

```
./manage run -d acapy
Agents to be used:
  Acme - acapy
  Bob - acapy
  Faber - acapy
  Mallory - acapy

No tags specified; all tests will be run.

Starting Acme Agent ...
Starting Bob Agent ...
Starting Faber Agent ...
Starting Mallory Agent ...

waiting for Acme agent to start..
waiting for Bob agent to start...
waiting for Faber agent to start
waiting for Mallory agent to start

Feature: Aries agent credential revocation and revocation notification RFC 0011 & 0183 # features/0011-0183-revocation.feature:1

  @T001-RFC0011 @P1 @AcceptanceTest @Schema_DriversLicense_Revoc @wip @NeedsReview
  Scenario Outline: Credential revoked by Issuer and Holder attempts to prove -- @1.1   # features/0011-0183-revocation.feature:19
    Given "3" agents                                                                    # features/steps/0160-connection.py:15 0.000s
      | name  | role     |
      | Acme  | issuer   |
      | Bob   | holder   |
      | Faber | verifier |
    And "Faber" and "Bob" have an existing connection                                   # features/steps/0160-connection.py:245 3.054s
    And "Bob" has an issued credential from “Acme" with Data_DL_MaxValues               # features/steps/0037-present-proof.py:6 0.003s
      Assertion Failed: FAILED SUB-STEP: Given "Bob" has an issued credential from “Acme"
      Substep info: Assertion Failed: FAILED SUB-STEP: Given "“Acme"" and "Bob" have an existing connection
      Substep info: Assertion Failed: FAILED SUB-STEP: When "“Acme"" generates a connection invitation
      Substep info: Traceback (most recent call last):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 61, in step_impl
          (resp_status, resp_
```

**Review by swcurran — CHANGES_REQUESTED** [review]
How can I make sure the revoc tests will run -- see my comment on the PR.

I also notice that there is not tag for a feature -- so that I can run all the tests for a single feature (e.g. revocation).  Is there a way to do that with command line parameters?  Config file?  Or should there be a tag for each feature?

**Comment by nodlesh** [comment]
@swcurran All features are separated by the feature file, for running specific features, add `include_re=0160-connection.feature` to the behave.ini file for example.

For the revocation tests, you need to be running the Tails Server. (At least I think that is what your problem is)
git clone https://github.com/bcgov/indy-tails-server
cd indy-tails-server/docker
./manage start

**Comment by swcurran** [comment]
Started the tails server, but I'm getting the same error:

```
Recreating docker_tails-server_1     ... done
Starting docker_ngrok-tails-server_1 ... done
Attaching to docker_ngrok-tails-server_1, docker_tails-server_1
ngrok-tails-server_1  | t=2020-10-29T21:05:54+0000 lvl=info msg="no configuration paths supplied"
ngrok-tails-server_1  | t=2020-10-29T21:05:54+0000 lvl=info msg="using configuration at default config path" path=/home/ngrok/.ngrok2/ngrok.yml
ngrok-tails-server_1  | t=2020-10-29T21:05:54+0000 lvl=info msg="open config file" path=/home/ngrok/.ngrok2/ngrok.yml err=nil
ngrok-tails-server_1  | t=2020-10-29T21:05:54+0000 lvl=info msg="starting web service" obj=web addr=0.0.0.0:4040
ngrok-tails-server_1  | t=2020-10-29T21:05:55+0000 lvl=info msg="tunnel session started" obj=tunnels.session
ngrok-tails-server_1  | t=2020-10-29T21:05:55+0000 lvl=info msg="client session established" obj=csess id=b4e8a8651ebf
ngrok-tails-server_1  | t=2020-10-29T21:05:55+0000 lvl=info msg="started tunnel" obj=tunnels name="command_line (http)" addr=http://tails-server:6543 url=http://9fb098c6583a.ngrok.io
ngrok-tails-server_1  | t=2020-10-29T21:05:55+0000 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=http://tails-server:6543 url=https://9fb098c6583a.ngrok.io
tails-server_1        | ======== Running on http://0.0.0.0:6543 ========
tails-server_1        | (Press CTRL+C to quit)
```

Error:

```
Feature: Aries agent credential revocation and revocation notification RFC 0011 & 0183 # features/0011-0183-revocation.feature:1

  @T001-RFC0011 @P1 @AcceptanceTest @Schema_DriversLicense_Revoc @wip @NeedsReview
  Scenario Outline: Credential revoked by Issuer and Holder attempts to prove -- @1.1   # features/0011-0183-revocation.feature:19
    Given "3" agents                                                                    # features/steps/0160-connection.py:15 0.000s
      | name  | role     |
      | Acme  | issuer   |
      | Bob   | holder   |
      | Faber | verifier |
    And "Faber" and "Bob" have an existing connection                                   # features/steps/0160-connection.py:245 3.053s
    And "Bob" has an issued credential from “Acme" with Data_DL_MaxValues               # features/steps/0037-present-proof.py:6 0.004s
      Assertion Failed: FAILED SUB-STEP: Given "Bob" has an issued credential from “Acme"
      Substep info: Assertion Failed: FAILED SUB-STEP: Given "“Acme"" and "Bob" have an existing connection
      Substep info: Assertion Failed: FAILED SUB-STEP: When "“Acme"" generates a connection invitation
      Substep info: Traceback (most recent call last):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 61, in step_impl
          (resp_status, resp_text) = agent_backchannel_POST(inviter_url + "/agent/command/", "connection", operation="create-invitation")
      TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 61, in step_impl
          (resp_status, resp_text) = agent_backchannel_POST(inviter_url + "/agent/command/", "connection", operation="create-invitation")
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 256, in step_impl
          ''')
        File "/usr/local/lib/python3.7/site-packages/behave/runner.py", line 404, in execute_steps
          assert False, message
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0037-present-proof.py", line 52, in step_impl
          ''')
        File "/usr/local/lib/python3.7/site-packages/behave/runner.py", line 404, in execute_steps
          assert False, message
```

**Comment by nodlesh** [comment]
Ok, I thought I had the wait increased enough waiting on the web hook callback in the backchannel. I have not gotten that problem since I increased the wait. I guess I'm going to have to put in a loop around that call and timeout and fail the test if the web hook never comes.

**Comment by swcurran** [comment]
Should I test again?

**Comment by nodlesh** [comment]
@swcurran @ianco 
Biggest thing here is a change to the algorithm to fix the TypeError that occasionally would happen if the web hook callbacks were slow, benefited performance substantially. Test execution time has been improved by ~80%.  Please retest and let me know how execution time has increased for you. 

Please be sure to run a tails server for the revocation tests,
git clone https://github.com/bcgov/indy-tails-server
cd indy-tails-server/docker
./manage start

and then run the tests as such, 
./manage run -d acapy -t @AcceptanceTest -t ~@wip

**Comment by nodlesh** [comment]
@swcurran noticed lgtm picked up a few more things. Will get that in now.

**Comment by nodlesh** [comment]
The remaining 2 LGTM alerts are IMO incorrect. The code is working.

**Review by ianco — APPROVED** [review]

**Review by swcurran — APPROVED** [review]
Nice!

**Pull request merged**
