### PR TITLE
Add backchannel for findy-agent

### PR DESCRIPTION
**Pull request by lauravuo-techlab**
Signed-off-by: Laura Vuorenoja <laura.vuorenoja@op.fi>

Add backchannel for testing compatibility with [Findy Agency](https://findy-network.github.io) agent. Current interoperability target for findy-agent is IOP1.0 excluding revocation.

### CODE REVIEW

**Review by swcurran — APPROVED** [review]
Awesome job.  I was going to confirm the tests that should be passing, but I see you have a runset ready to go -- excellent.  I ran the Findy Test Agent running all tests and assumed what you are saying -- AIP 1.0 and no revocation.  Perfect.

Would love to have any feedback you have about the AATH -- things we could improve?

**Comment by nodlesh** [comment]
3 allure projects have been created here, https://allure.vonx.io/allure-docker-service-ui/
`findy`
`findy-b-acapy`
`acapy-b-findy`

**Comment by swcurran** [comment]
Please add a findy-afj-dotnet project as well (a/m, b, f respectively).

**Comment by nodlesh** [comment]
So an allure project named `findy-b-afj-f-dotnet`?

**Comment by swcurran** [comment]
Sure

**Comment by nodlesh** [comment]
Done

**Comment by lauravuo-techlab** [comment]
@swcurran 

Thanks for reviewing this so promptly!

I think AATH is an excellent tool for testing interoperability and even functionality in general. We integrated the tests also to our findy-agent release pipeline – agent release is not happening if the AATH tests are not passing, so we can easily catch e.g. regression with our client APIs.

This was my first time when I used openapi specification based code generation – I think it also worked rather well and eased the developer job when starting with a new backchannel from scratch.

Some improvements that came to mind along the way:
* It would be excellent if the test script would support running agent and backchannel in different containers. We have a microservice architecture and running agent needs both the core service (findy-agent) and the auth service (findy-agent-auth). Now I need to bundle the three services (core, auth, backchannel) into a single AATH-dedicated image. Instead, I’d rather use image per service as we have the service images already built in our Docker registry. There would be no need to build the images for the test run, just pull them from the registry. This model would also ensure that the tests are run with exactly the same image as which the deployment is using (not only the same version of the codes).
* As we are using AATH also for regression testing, I was wondering if there is a parameter or switch for the manage-script that would stop the execution on failure and return an error code? Currently I am just checking that the test output contains some magic string to confirm that the test was successful, but it would be better to 1) save time if tests fail 2) fail CI pipeline automatically (shell cmd to return error)
* We aim to build the findy-agent client API such that it has minimal amount of direct indy-related features. The target is to hide the underlying technology from the client, so that we can add other credential formats in the future without the need to refactor the API too much. One thing in the AATH/acapy test logic was against this principle – the need to define attribute ids in proof requests. I guess this shouldn’t be necessary – the proof request attribute ids is really something that indy-sdk requires, but the client shouldn’t be bothered. However, a small thing and we added the the support for setting the id, so no actual obstacles there.

**Comment by swcurran** [comment]
Interesting comments -- thanks for sharing them.  I'll start with the first.

The "one container" approach was to make a consistent interface for of the Test Agents (where TA is the Backchannel+Whatever is being Tested). It allows us to just have a single way to start each Agent (E.g. Acme or Bob) without worrying about any details of the specific implementation.  We did give some consideration that each TA could be a docker-compose file, and the "./manage" script could assemble the docker-compose pieces at runtime to a complete docker-compose file to be run...but we think that's even worse.   While we know the intention of a container is to put one thing in it to aid in management in real environments, it's not a requirement, especially in a test environment like this.  I do agree that it feels odd to put everything into one container.

We could have the backchannel in one container, and the "thing being tested" in another, but I don't think that helps you, as you would have to put "everything else" into the one container.  It's really not too different.

So, I'd say we're not likely to pursue the idea of multi-container TAs unless someone has a clever, manageable way to do this. If you have an idea for that, let us know and we'll rethink this.

**Comment by swcurran** [comment]
I think adding a parameter to "stop on error" would be a good idea and happy to see that in the backlog.  Since our default approach is to run all tests and always push the pass/fail results to Allure (test results repository), a fail status on the test run would mean the results don't get to Allure.  However, if we aren't running with Allure, an error status would make sense.

Happy to see that in the backlog.

**Comment by swcurran** [comment]
It would be good to get a little more detail on the third issue.  I think I get it, but if you could highlight a specific example, that would be helpful.  In general, I agree with hiding details that are not needed in the backchannel API makes sense.

**Comment by lauravuo-techlab** [comment]
Thanks @swcurran! I will create issues for our findings with more elaborate descriptions. What comes to the first bullet, I don't have any better ideas (yet). It's a shame we cannot run docker-compose in a docker container 😄

**Comment by WadeBarnes** [comment]
> It's a shame we cannot run docker-compose in a docker container

You can, here is an example of a docker-compose container being built and then used to build another image using docker-compose in the container.  https://github.com/hyperledger/indy-test-automation/blob/main/system/docker/prepare.sh#L68-L85

**Comment by WadeBarnes** [comment]
It would require some work to AATH, but I think it would be possible to define a multi-container TA in a docker-compose file and then have AATH start that up in a docker-in-docker image that has docker-compose installed (as in the above example).  Both would use a defined network (also in the example above) allowing AATH to communicate with the backchannel which in-turn would communicate with the other TA components.  Then each TA could be defined using it's own docker-compose file and container/network topology.

**Pull request merged**
