### PR TITLE
Add Faber to the manage script, including usage and -f CLI parameter

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Comment by swcurran** [comment]
It was super simple to add and seems to work. It runs all the tests you created for presentation.  @nodlesh please compare against what you have running locally.

**Comment by ianco** [comment]
Faber agent seems to work, but I'm getting a lot of test failures:

0 features passed, 3 failed, 0 skipped
9 scenarios passed, 34 failed, 0 skipped
181 steps passed, 14 failed, 109 skipped, 51 undefined
Took 3m18.512s

Same results with `./manage run -d acapy` and `./manage run -d acapy-master`

**Comment by swcurran** [comment]
I think that is because of the tests. If you look at the Present Proof test, there is a test per data type, and all of them fail.

@nodlesh --- can you check on your side if the summary of results that @ianco found is accurate.

**Comment by nodlesh** [comment]
@ianco @swcurran Remember to only run the @acceptancetests and without @wip. 
./manage run -d acapy -t @AcceptanceTest -t ~@wip

**Comment by ianco** [comment]
`./manage run -d acapy -t @AcceptanceTest -t ~@wip` gives me:

3 features passed, 0 failed, 0 skipped
9 scenarios passed, 0 failed, 34 skipped
95 steps passed, 0 failed, 260 skipped, 0 undefined
Took 1m47.256s

**Review by ianco — APPROVED** [review]

**Review by nodlesh — APPROVED** [review]
Looks good running locally. 

Couple of things for the future.
- If 1-n agents don't start successfully, we should probably end the script
- You can't pass through other Behave command line arguments It would be nice to b e able to use the full list of arguments as a pass through to execution.

**Comment by swcurran** [comment]
@nodlesh -- to use the full behave command line, you can create a behave.ini file that has the arguments.  Passing them through multiple layers if "tricky" and unsatisfactorily.  That's in the docs on how to do that.   The behave.ini file can be local and .gitignore'd so it doesn't go into the repo.

**Comment by nodlesh** [comment]
@swcurran Got it. Forgot about the ini file.

**Pull request merged**
