### PR TITLE
[#530] Add script for improved feature/scenario display

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by swcurran** [comment]
I was not able to get it working -- I just get the initial `Selecting by: ['AIP20']` no matter what I pick.

I'm using Python 3.6.9 -- perhaps that's my problem?  I've not changed that in a long time...  :-).

**Comment by tdiesler** [comment]
Unfortunately, I can't downgrade that far ...

```
$ brew install python@3.6.9
Warning: No available formula with the name "python@3.6.9". Did you mean python@3.9, python@3.8, python@3.7 or python@3.10?
==> Searching for similarly named formulae...
These similarly named formulae were found:
python@3.9                                             python@3.8                                             python@3.7                                             python@3.10 ✔
```

I suspect you forgot the '@'. It uses the same tag syntax as with `./manage test` i.e.

```
./manage test -d acapy -b camel -t @T001-RFC0160,@T003-RFC0036,@T001-RFC0037
```

Multiple tags are separated by comma (no space in between)

```
$ ./manage tests -t @AIP20 -md
Selecting by: ['@AIP20']

| Status | Feature: RFC 0023 Establishing Connections with DID Exchange
|:------:|:-------------------------------------------------------------|
|        |  @T001-RFC0023
|        |  Scenario: Establish a connection with DID Exchange between two agents with an explicit invitation
|        |  @T003-RFC0023
|        |  Scenario: Establish a connection with DID Exchange between two agents with an explicit invitation with a public DID
|        |  @T005-RFC0023
|        |  Scenario: Establish a connection with DID Exchange between two agents with an implicit invitation
|        |  @T007-RFC0023
|        |  Scenario: Establish a connection with DID Exchange between two agents with attempt to continue after protocol is completed
|        |  @T008-RFC0023
|        |  Scenario: Establish a connection with DID Exchange between two agents with an explicit invitation but invitation is rejected and connection process restarted
|        |  @T009-RFC0023
|        |  Scenario: Establish a connection with DID Exchange between two agents with an explicit invitation but invitation is rejected and connection process abandoned
|        |  @T010-RFC0023
|        |  Scenario: Establish a connection with DID Exchange and responder rejects the request
|        |  @T011-RFC0023
|        |  Scenario: Establish a connection with DID Exchange and requester rejects the response
|        |  @T012-RFC0023
|        |  Scenario: Attempt to Establish a connection with DID Exchange between two agents with an explicit invitation with connection reuse

| Status | Feature: RFC 0025 DIDComm Transports
|:------:|:-------------------------------------|
|        |  @T001-RFC0025
|        |  Scenario: Create DIDExchange connection between two agents with overlapping transports
...
```

**Comment by tdiesler** [comment]
I made the leading '@' optional, as it is with `./manage test` - sorry, I missed that. This should now work ...

```
$ ./manage tests -t AIP20,@AIP10
```

Please try again

**Comment by swcurran** [comment]
There is a conflict and I can't test this.  Could you please address that?  When I try to check out, I get this, which I assume is from the conflict: 

```
~/repos/aries-agent-test-harness [main] 11:23 $ gh pr checkout 541
From https://github.com/hyperledger/aries-agent-test-harness
 ! [rejected]        refs/pull/541/head -> ghi530  (non-fast-forward)
exit status 1
```

**Comment by tdiesler** [comment]
I follow a "one-commit per issue" policy. In that way, it is easy to see what has actually changed for any given issue and cherry picks don't span over multiple commits. As long as a PR branch is not merged, I rebase (rather than merge) and use forced pushes when needed. Folks who work with me on theses (throw away) feature branches know that repeated pulls (i.e. fast-forward) may not work because of this. Its easy to fix ...

```
git reset --hard [upstream-head-rev]
git pull [source-repo]
```

Alternatively, you can throw away your checkout branch and fetch again from [source-repo].

**Comment by tdiesler** [comment]
origin main is always a parent of any given feature branch (also of ghi530)

**Comment by swcurran** [comment]
To fix on my fork, I deleted the branch and then reran the `gh` checkout command:

```
git branch -D ghi530
gh pr checkout 541
```

**Review by swcurran — CHANGES_REQUESTED** [review]
One more tweak, please. Suggest updating the help (manage script, line 118) to include a bit about the options supported  I think it is just `-t` in the same style as `run` (or can there be only one -t included?), and the `-m` option for the markdown.  I checked the help to learn how to do the latter, and noticed it wasn't there.  Are there any other supported options?  I would assume not...

**Comment by tdiesler** [comment]
you got it ... help now reads ...

```
$ ./manage tests -h
               
usage: scenarios.py [-h] -t TAGS [-md]

Scan feature files for tagged test scenarios

options:
  -h, --help            show this help message and exit
  -t TAGS, --tags TAGS  Comma separated list of tags (e.g. AIP10,AIP20)
  -md, --markdown       Display result as markdown table
```

Multiple occurrences of the same option are not supported by [argparse](https://docs.python.org/3/library/argparse.html). I tried it and seems that the latter (silently) overrides the former. 

```
$ ./manage tests -t AIP10 -t AIP20
Namespace(tags='AIP20', markdown=False)
Selecting by: ['@AIP20']
...
```

**Comment by swcurran** [comment]
I like the help, but still missing the help for the main "usage()" message -- [this line](https://github.com/hyperledger/aries-agent-test-harness/blob/d678e4b4432ab08bacbb7925a885e2a417bf837c/manage#L118) in the usage.  If you disagree, I'm happy to merge without.

I really like your subcommand help, and we really need to add that and cut down on the  "all-in-one" usage.  I'll add an issue and see about getting that done.

**Comment by tdiesler** [comment]
... [like so](https://github.com/tdiesler/aries-agent-test-harness/blob/ghi530/manage#L118)? 
Feel free to change in any way you like.

**Review by swcurran — APPROVED** [review]
Thanks -- sorry it's taken so long to merge.

**Pull request merged**
