### PR TITLE
Support afgo-acapy RFC0453 interop, and fix 0023 interop issues

### PR DESCRIPTION
**Pull request by Moopli**
AFGO-ACAPy interop tests that are now enabled:
- all didexchange tests 
- all JSON-LD issue-credential tests, with the exception of BBS+ with ACA-Py issuer, as there's an intermittent error where ACA-Py gets the public orb DID of the afgo holder instead of a peer DID.

### CODE REVIEW

**Comment by swcurran** [comment]
w00t!  We'll check this out!

**Comment by Moopli** [comment]
Waiting on https://github.com/hyperledger/aries-framework-go/pull/2992 before marking this as ready for review, since the didexchange tests will still see errors until that's in.

**Comment by Moopli** [comment]
All tests are passing:
- [Acme ACA-Py, Bob AFGO](https://github.com/Moopli/aries-agent-test-harness/runs/3676966567?check_suite_focus=true#step:6:1699)
- [Acme AFGO, Bob ACA-Py](https://github.com/Moopli/aries-agent-test-harness/runs/3676969146?check_suite_focus=true#step:6:1699)
- [AFGO-AFGO](https://github.com/Moopli/aries-agent-test-harness/runs/3676972099?check_suite_focus=true#step:6:530)

Marking this ready for review!

**Comment by swcurran** [comment]
Running locally, I'm getting errors `No such file or directory: '/data-mount/orb-dids/Acme.json'`.   Do we need to be creating a directory before starting to get this working?  Looks like it is created in orb wrapper.sh?

**Comment by nodlesh** [comment]
Getting the same thing. Already made Filip aware. I know the fix, because we had this before.

**Comment by nodlesh** [comment]
If you wish to try the tests before this the fix is committed, you can remove the trailing slash at the end of these lines in services/orb/wrapper.sh
```
	cp -r .build/orb-dids ../../aries-backchannels/afgo/.build/afgo-master.data/
	cp -r .build/orb-dids ../../aries-backchannels/afgo/.build/afgo-interop.data/
	cp -r did-keys/priv ../../aries-backchannels/afgo/.build/afgo-master.data/
	cp -r did-keys/priv ../../aries-backchannels/afgo/.build/afgo-interop.data/
```

**Comment by Moopli** [comment]
@swcurran fixed
edit: also do `./manage service start orb` to start orb

**Comment by nodlesh** [comment]
@Moopli I think the environment.properties needs to be there for now. At this time the manage script expects it to be there. 2 options here, add the file back in, or you can modify the manage script to write the file instead of expecting it to exist.

**Comment by Moopli** [comment]
removed the commit in question :) @nodlesh

**Review by nodlesh — APPROVED** [review]
Everything is passing for me. This is great progress. 👍

**Pull request merged**
