### PR TITLE
Aries Framework JavaScript connections topic

### PR DESCRIPTION
**Pull request by TimoGlastra**
Pretty excited about this one :)

This PR adds the initial setup for the aries-framework-javascript (AFJ) backchannel with the connection operations working with both ACA-Py and .NET.

For now a slightly modified version of the framework is packaged with the backchannel because of some interoperability issues between AFJ and ACA-Py. I'll need to look a bit deeper, but I'll either make the necessary changes in AFJ or create an issue in ACA-Py.

One note: I needed to add a `.dockerignore` file to the `aries-backchannels` directory because that's where the images are build from (instead of the `aries-backchannels/javascript` directory). Not a big problem, but means backchannel specific parts are stored outside of the backchannel directory.

---

FYI @jakubkoci @karimStekelenburg @jadhavajay

### CODE REVIEW

**Comment by swcurran** [comment]
w00t!!

**Comment by TimoGlastra** [comment]
opened hyperledger/aries-cloudagent-python#711 to address interoperability issue

**Review by swcurran — APPROVED** [review]
LGTM - ran tests.

**Comment by TimoGlastra** [comment]
I'm not sure how many CI minutes the Hyperledger account has to spare, but if you would like I could set up a GitHub actions pipeline to automatically run on PRs. Would save you some time on the repetitive local test runs ;)

**Pull request merged**
