### PR TITLE
feat: integrate orb did method

### PR DESCRIPTION
**Pull request by Moopli**
Adds `orb`, a new service, which runs a small orb network and a
universal resolver orb driver instance.

Integrates the service with the afgo backchannel, by having the service
create an orb did and save the value in a data folder for the afgo backchannel
to load.

Adds a general way to load files into agent containers:
A directory named <agent-name>.data (eg, afg-master.data), if present within the
backchannel's folder, will be mounted as a volume within the given agent,
to the path `/data-mount`.

Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

### CODE REVIEW

**Comment by swcurran** [comment]
Very cool!

**Review by fqutishat — DISMISSED** [review]

**Comment by nodlesh** [comment]
I was running through this PR to see if there were any negative side effects on standard running acapy or other agents. Looks good. However, I do get some tests (2) that normally pass, failing with afgo/afgo. The 2 failures are the same. 
```
Given "Acme" has a public did                                                               # features/steps/0036-issue-credential.py:30 0.027s
      Assertion Failed: resp_status 400 is not 200; {"did": "did:orb:interim:EiC-APyPe_jdkVXr6QMg8DEG1fI5RDVSBTXyL9BIqepFRA"}'
```
Is there something I should be doing to get these afgo tests to work? Maybe this is only suppose to work with your other PR? 
My command to execute the afgo tests is `./manage run -d afgo-master -t @RFC0023,@T001.1-RFC0036,@RFC0453,@RFC0454 -t ~@wip -t ~@T003-RFC0023 -t ~@T004-RFC0023  -t ~@T005-RFC0023 -t ~@T006-RFC0023 -t ~@CredFormat_JSON-LD`

**Comment by Moopli** [comment]
@nodlesh it looks like the issue is with the "has a public did" step being run more than once on the same agent instance - I'll update the afgo backchannel in https://github.com/hyperledger/aries-agent-test-harness/pull/281 to fix that.

Closing this PR in favor of https://github.com/hyperledger/aries-agent-test-harness/pull/281, since I've made further changes to the orb configuration there, as well as followup integration work to use orb in the implicit invitation tests.

**Comment by Moopli** [comment]
Opened a new PR for orb: https://github.com/hyperledger/aries-agent-test-harness/pull/288

**Pull request closed without merging**
