### PR TITLE
Update aries-vcx backchannel - aries_vcx: 62.0.1+

### PR DESCRIPTION
**Pull request by Patrik-Stas**

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
Hi @nodlesh is there a way to trigger CI run for this before merging?

**Comment by swcurran** [comment]
The easiest way (that I’m running now) is to make the updates, or update to the current PR (e.g. `gh pr checkout 778`, and then to run:

`./manage runset ariesvcx-ariesvcx -b`

It `runset` looks up the workflows and executes the steps of the one you specify.  The `-b` does a build, and you can do a `-r` (rebuild) or `-n` (dry run — show what would run).  Use `./manage runset` to get the options and the list of jobs you can run.

I’m running it now…will let you know the results.

**Comment by swcurran** [comment]
It didn’t go well @Patrik-Stas — the agents failed to start.  The logs each just contained this:

```
Hello, world!


```

**Comment by swcurran** [comment]
I assume you can now test on your own, but after the latest commits — same result.

**Comment by gmulhearn-anonyome** [comment]
fyi: i'll take over this PR in coming week

**Pull request closed without merging**
