### PR TITLE
Update services for cleaner execution and afgo-acapy interop support

### PR DESCRIPTION
**Pull request by Moopli**

### CODE REVIEW

**Comment by swcurran** [comment]
When I run `/manage service start orb`, things go well for most of the process, and then I get this error:

```
Creating orb.driver      ... done
Creating orb.domain2.com ... done
Creating orb.domain1.com ... done
Unable to find image 'ubuntu:20.04' locally
20.04: Pulling from library/ubuntu
d7bfe07ed847: Pull complete 
Digest: sha256:fd92c36d3cb9b1d027c4d2a72c6bf0125da82425fc2ca37c414d4f010180dc19
Status: Downloaded newer image for ubuntu:20.04
success Follow id: "https://orb.domain2.com/services/orb/activities/09cfcd6b-19d8-4b68-8e75-042dac894192"
Error: failed to get services from file json: cannot unmarshal array into Go struct field Service.serviceEndpoint of type string
Usage:
  orb-cli did create [flags]

Flags:
      --did-anchor-origin string      did anchor origin  Alternatively, this can be set with the following environment variable: ORB_CLI_DID_ANCHOR_ORIGIN
      --domain string                 URL to the did:orb domain.  Alternatively, this can be set with the following environment variable: ORB_CLI_DOMAIN
  -h, --help                          help for create
      --publickey-file string         publickey file include public keys for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_PUBLICKEY_FILE
      --recoverykey string            The public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY
      --recoverykey-file string       The file that contains the public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY_FILE
      --service-file string           publickey file include services for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_SERVICE_FILE
      --sidetree-url stringArray      Comma-Separated list of sidetree url. Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_URL
      --sidetree-write-token string   The sidetree write token  Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_WRITE_TOKEN
      --tls-cacerts stringArray       Comma-Separated list of ca certs path. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_CACERTS
      --tls-systemcertpool string     Use system certificate pool. Possible values [true] [false]. Defaults to false if not set. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_SYSTEMCERTPOOL
      --updatekey string              The public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY
      --updatekey-file string         The file that contains the public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY_FILE

Error: failed to get services from file json: cannot unmarshal array into Go struct field Service.serviceEndpoint of type string
Usage:
  orb-cli did create [flags]

Flags:
      --did-anchor-origin string      did anchor origin  Alternatively, this can be set with the following environment variable: ORB_CLI_DID_ANCHOR_ORIGIN
      --domain string                 URL to the did:orb domain.  Alternatively, this can be set with the following environment variable: ORB_CLI_DOMAIN
  -h, --help                          help for create
      --publickey-file string         publickey file include public keys for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_PUBLICKEY_FILE
      --recoverykey string            The public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY
      --recoverykey-file string       The file that contains the public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY_FILE
      --service-file string           publickey file include services for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_SERVICE_FILE
      --sidetree-url stringArray      Comma-Separated list of sidetree url. Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_URL
      --sidetree-write-token string   The sidetree write token  Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_WRITE_TOKEN
      --tls-cacerts stringArray       Comma-Separated list of ca certs path. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_CACERTS
      --tls-systemcertpool string     Use system certificate pool. Possible values [true] [false]. Defaults to false if not set. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_SYSTEMCERTPOOL
      --updatekey string              The public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY
      --updatekey-file string         The file that contains the public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY_FILE

Error: failed to get services from file json: cannot unmarshal array into Go struct field Service.serviceEndpoint of type string
Usage:
  orb-cli did create [flags]

Flags:
      --did-anchor-origin string      did anchor origin  Alternatively, this can be set with the following environment variable: ORB_CLI_DID_ANCHOR_ORIGIN
      --domain string                 URL to the did:orb domain.  Alternatively, this can be set with the following environment variable: ORB_CLI_DOMAIN
  -h, --help                          help for create
      --publickey-file string         publickey file include public keys for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_PUBLICKEY_FILE
      --recoverykey string            The public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY
      --recoverykey-file string       The file that contains the public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY_FILE
      --service-file string           publickey file include services for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_SERVICE_FILE
      --sidetree-url stringArray      Comma-Separated list of sidetree url. Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_URL
      --sidetree-write-token string   The sidetree write token  Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_WRITE_TOKEN
      --tls-cacerts stringArray       Comma-Separated list of ca certs path. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_CACERTS
      --tls-systemcertpool string     Use system certificate pool. Possible values [true] [false]. Defaults to false if not set. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_SYSTEMCERTPOOL
      --updatekey string              The public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY
      --updatekey-file string         The file that contains the public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY_FILE

Error: failed to get services from file json: cannot unmarshal array into Go struct field Service.serviceEndpoint of type string
Usage:
  orb-cli did create [flags]

Flags:
      --did-anchor-origin string      did anchor origin  Alternatively, this can be set with the following environment variable: ORB_CLI_DID_ANCHOR_ORIGIN
      --domain string                 URL to the did:orb domain.  Alternatively, this can be set with the following environment variable: ORB_CLI_DOMAIN
  -h, --help                          help for create
      --publickey-file string         publickey file include public keys for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_PUBLICKEY_FILE
      --recoverykey string            The public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY
      --recoverykey-file string       The file that contains the public key PEM used for recovery of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_RECOVERYKEY_FILE
      --service-file string           publickey file include services for Orb DID  Alternatively, this can be set with the following environment variable: ORB_CLI_SERVICE_FILE
      --sidetree-url stringArray      Comma-Separated list of sidetree url. Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_URL
      --sidetree-write-token string   The sidetree write token  Alternatively, this can be set with the following environment variable: ORB_CLI_SIDETREE_WRITE_TOKEN
      --tls-cacerts stringArray       Comma-Separated list of ca certs path. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_CACERTS
      --tls-systemcertpool string     Use system certificate pool. Possible values [true] [false]. Defaults to false if not set. Alternatively, this can be set with the following environment variable: ORB_CLI_TLS_SYSTEMCERTPOOL
      --updatekey string              The public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY
      --updatekey-file string         The file that contains the public key PEM used for validating the signature of the next update of the document. Alternatively, this can be set with the following environment variable: ORB_CLI_UPDATEKEY_FILE


```

**Comment by swcurran** [comment]
Lots of the acapy-afgo tests are passing, but some aren't, such as "@T005-RFC0023 @critical @AcceptanceTest
  Scenario: Establish a connection with DID Exchange between two agents with an implicit invitation".  I suspect the issue with that is the failure to create the did:orb DIDs in my previous message ^^^.

**Comment by swcurran** [comment]
Looks good - just one failed scenario.  Hopefully the service start issue can be addressed and we can merge.

**Comment by Moopli** [comment]
@swcurran delete the `services/orb/.build` folder, so orb starts from a clean setup

Otherwise, the older version of orb-cli is still in the folder, and will be used, instead of the script downloading an updated version.

**Comment by swcurran** [comment]
That fixed the `start orb` issue.  However, the same test fails -- just two steps later than before.

```
 @T005-RFC0023 @critical @AcceptanceTest
  Scenario: Establish a connection with DID Exchange between two agents with an implicit invitation  # features/0023-did-exchange.feature:45
    Given we have "2" agents                                                                         # features/steps/0160-connection.py:22 0.000s
      | name | role      |
      | Acme | requester |
      | Bob  | responder |
    And "Bob" has a resolvable DID                                                                   # features/steps/0023-did-exchange.py:87 0.057s
    And "Acme" acquires the resolvable DID                                                           # features/steps/0023-did-exchange.py:100 0.000s
    When "Acme" sends the request to "Bob" with the public DID                                       # features/steps/0023-did-exchange.py:106 0.338s
      Assertion Failed: resp_status 500 is not 200; 500 Internal Server Error
      
      Server got itself in trouble

    And "Bob" receives the request with their public DID                                             # None
    When "Bob" sends a response to "Acme"                                                            # None
    And "Acme" receives the response                                                                 # None
    And "Acme" sends complete to "Bob"                                                               # None
    Then "Acme" and "Bob" have a connection      
```

I'm running `./manage service start orb` and then the `./manage run....` command.  Is there any other services I need to be running that aren't started on every run?

**Comment by Moopli** [comment]
@swcurran that's this error: https://github.com/hyperledger/aries-agent-test-harness/issues/502#issuecomment-1148920667

**Comment by Moopli** [comment]
@swcurran 
> I'm running `./manage service start orb` and then the `./manage run....` command. Is there any other services I need to be running that aren't started on every run?

No, orb is currently the only service that isn't started by default - I'd like indy-tails and VON to be started only when needed also, but that's not the case atm.

**Comment by swcurran** [comment]
Sounds good -- I was wondering that :-).

I'll add an explcit ticket for @dbluhm with the details.

**Review by swcurran — APPROVED** [review]

**Comment by Moopli** [comment]
The only interop errors left should be:
- acapy-b-afgo T005-RFC0023: acapy rejects new DID service endpoint syntax, as noted, issue #509 
- afgo-b-acapy T007-RFC0023: acapy is running in auto-accept mode, issue #456

**Pull request merged**
